<a href="https://colab.research.google.com/github/Flociah/Karamoja-Project/blob/main/Karamoja_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#KARAMOJA PROJECT.

The Karamoja region of Uganda faces severe food insecurity, primarily due to low crop productivity driven by intense droughts and frequent pest and disease outbreaks. To address these challenges, several NGOs provide technical support and farm inputs to the farmers, but they often lack comprehensive visibility into the region's overall state. To aid in better decision-making, Dalberg Data Insights (DDI) was tasked with developing a food security monitoring tool, leveraging satellite images to remotely measure the yield of the two main staple crops in the region: sorghum and maize.

## DATA UNDERSTANDING

The data provided by DDI includes a variety of features, such as shapefiles for the boundaries of Uganda's subcounties and districts, maps indicating the locations of sorghum and maize fields, and tables containing crop production data, yield, and population statistics. Key features of the dataset include total population, average yield for sorghum and maize, crop area, and total productivity for each subcounty and district.
Below is a summary of the provided data:

Shapefiles

Boundaries of Uganda Subcounties

Boundaries of Uganda Districts

Crop Type Map for Sorghum (i.e. position of the Sorghum fields)

Crop Type Map for Maize(i.e positio of the maize fields)

Tables containing the cproduction of the crops

Yield and Population per Subcounty

POP: total population for the subcounty

S_Yield_Ha: average yield for sorghum for the subcounty (Kg/Ha)

M_Yield_Ha: average yield for maize for the subcounty (Kg/Ha)

Crop_Area_Ha: total crop area for the subcounty (Ha)

S_Area_Ha: total sorghum crop area for the subcounty (Ha)

M_Area_Ha: total maize crop area for the subcounty (Ha)

S_Prod_Tot: total productivity for the sorghum for the subcounty (Kg)

M_Prod_Tot: total productivity for the maize for the subcounty (Kg)

Yield and Population per District

## DATA PREPARATION
The libraries are imported first for structuring of the code effectively.
- This will also allow reuse of the code while keeping the project maintainable.

In [51]:
#Importing of the libraries
import pandas as pd
import numpy as np

In order to read our data generated in the format preferred by Excel, it is important to use CSV reader. The pandas read_csvs() function returns a new Dataframe with data and labels from the file data.

In [52]:
# Allocation of a variables to district data
dist_df =pd.read_csv("/content/Uganda_Karamoja_District_Crop_Yield_Population.csv")
dist_df.head(10)

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,92,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567
1,96,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558
2,20,KAABONG,627057,7373606003,279,945,28121.672530,20544.194960,7394.416334,5731830,6987723
3,85,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575
4,5,MOROTO,127811,3570160948,128,355,5954.814048,4741.748776,1190.050606,606944,422468
5,54,NAKAPIRIPIRIT,146780,4216323900,356,1264,26372.698490,19237.333210,6425.788414,6848491,8122197
6,80,NAPAK,167625,4508782023,137,854,22944.296020,16142.015880,6543.719066,2211456,5588336

In [53]:
# Allocation of a variables to district data

subc_df =pd.read_csv("/content/Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv")
subc_df.head(10)

,OBJECTID,SUBCOUNTY_NAME,DISTRICT_NAME,POP,Area,Karamoja,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,263,KACHERI,KOTIDO,17244,1067176155,Y,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,600723.892900
1,264,KOTIDO,KOTIDO,52771,597575188,Y,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,959201.382500
2,265,KOTIDO TOWN COUNCIL,KOTIDO,27389,23972401,Y,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9991.488268
3,266,NAKAPERIMORU,KOTIDO,38775,419111591,Y,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,38971.659080
4,267,PANYANGARA,KOTIDO,65704,880955930,Y,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,221609.511400
5,268,RENGEN,KOTIDO,41273,652744859,Y,271.185843,1047.180128,13278.520430,12964.499730,171.585704,3.515789e+06,179681.139000
6,591,KAABONG EAST,KAABONG,42221,60801942,Y,160.588525,650.123565,1021.316990,1004.647534,15.660409,1.613349e+05,10181.201000
7,592,KAABONG TOWN COUNCIL,KAABONG,38857,13071455,Y,212.210703,1229.213444,175.080527,156.503888,18.526186,3.321180e+04,22772.636430
8,593,KAABONG WEST,KAABONG,41454,67612362,Y,208.040518,1056.416068,967.336727,910.254122,56.275355,1.893697e+05,59450.189420
9,594,KALAPATA,KAABONG,99203,223116860,Y,209.809352,633.423182,2834.349905,2501.368282,331.225795,5.248105e+05,209806.097000

## Data Exploration
understanding the structure, quality, and underlying patterns within the dataset

In [54]:
# Understanding the sizes of our datasets through rows and columns
[dist_df.shape,subc_df.shape]

[(7, 11), (52, 13)]

In [55]:
# Summary of the district dataset
dist_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OBJECTID      7 non-null      int64
 1   NAME          7 non-null      object
 2   POP           7 non-null      int64
 3   Area          7 non-null      int64
 4   S_Yield_Ha    7 non-null      int64
 5   M_Yield_Ha    7 non-null      int64
 6   Crop_Area_Ha  7 non-null      float64
 7   S_Area_Ha     7 non-null      float64
 8   M_Area_Ha     7 non-null      float64
 9   S_Prod_Tot    7 non-null      int64
 10  M_Prod_Tot    7 non-null      int64
dtypes: float64(3), int64(7), object(1)
memory usage: 744.0+ bytes

In [56]:
# Summary of the sub-county dataset
subc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBJECTID        52 non-null     int64
 1   SUBCOUNTY_NAME  52 non-null     object
 2   DISTRICT_NAME   52 non-null     object
 3   POP             52 non-null     int64
 4   Area            52 non-null     int64
 5   Karamoja        52 non-null     object
 6   S_Yield_Ha      52 non-null     float64
 7   M_Yield_Ha      52 non-null     float64
 8   Crop_Area_Ha    52 non-null     float64
 9   S_Area_Ha       52 non-null     float64
 10  M_Area_Ha       52 non-null     float64
 11  S_Prod_Tot      52 non-null     float64
 12  M_Prod_Tot      52 non-null     float64
dtypes: float64(7), int64(3), object(3)
memory usage: 5.4+ KB

## DATA CLEANING

Data cleaning involves checking out for missing values, duplicates and handling missing data to make the data reliable and accurate foe decision making.

In [57]:
#Checking for null values in the district
dist_df.isnull().sum()

OBJECTID        0
NAME            0
POP             0
Area            0
S_Yield_Ha      0
M_Yield_Ha      0
Crop_Area_Ha    0
S_Area_Ha       0
M_Area_Ha       0
S_Prod_Tot      0
M_Prod_Tot      0
dtype: int64

In [58]:
# Checking for duplicate values.
dist_df.duplicated().sum()

0

 **Findings** : District Data has no duplicates and misssing values
 if found clean data

In [59]:
# Checking for null values in the sub-county level
subc_df.isnull().sum()

OBJECTID          0
SUBCOUNTY_NAME    0
DISTRICT_NAME     0
POP               0
Area              0
Karamoja          0
S_Yield_Ha        0
M_Yield_Ha        0
Crop_Area_Ha      0
S_Area_Ha         0
M_Area_Ha         0
S_Prod_Tot        0
M_Prod_Tot        0
dtype: int64

In [60]:
# Checking for duplicate values.
subc_df.duplicated().sum()

0

 #### **Findings** :
 Subcounty Data has no duplicates and misssing values
 if found clean data

## Merging of the datasets.

Merging of the Sub-County and District dataset is important in order to allow analysis in the Tableau work tool easier.

In [66]:

# combining the data frames by columns
combined_df = pd.merge(dist_df, subc_df, how='outer')
combined_df.head(12)

<ipython-input-66-51cd3050a691>:2: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  combined_df = pd.merge(dist_df, subc_df, how='outer')

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot,SUBCOUNTY_NAME,DISTRICT_NAME,Karamoja
0,92,ABIM,90385,2771977106,449.000000,1040.000000,5470.068394,3277.295971,1848.621855,1.471506e+06,1.922567e+06,NaN,NaN,NaN
1,96,AMUDAT,101790,1643582836,205.000000,1297.000000,5765.443719,2973.423860,2733.661014,6.095520e+05,3.545558e+06,NaN,NaN,NaN
2,20,KAABONG,627057,7373606003,279.000000,945.000000,28121.672530,20544.194960,7394.416334,5.731830e+06,6.987723e+06,NaN,NaN,NaN
3,85,KOTIDO,243157,3641539808,331.000000,1148.000000,53032.649450,50247.443900,1751.372284,1.663190e+07,2.010575e+06,NaN,NaN,NaN
4,5,MOROTO,127811,3570160948,128.000000,355.000000,5954.814048,4741.748776,1190.050606,6.069440e+05,4.224680e+05,NaN,NaN,NaN
5,54,NAKAPIRIPIRIT,146780,4216323900,356.000000,1264.000000,26372.698490,19237.333210,6425.788414,6.848491e+06,8.122197e+06,NaN,NaN,NaN
6,80,NAPAK,167625,4508782023,137.000000,854.000000,22944.296020,16142.015880,6543.719066,2.211456e+06,5.588336e+06,NaN,NaN,NaN
7,263,NaN,17244,1067176155,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,6.007239e+05,KACHERI,KOTIDO,Y
8,264,NaN,52771,597575188,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,9.592014e+05,KOTIDO,KOTIDO,Y
9,265,NaN,27389,23972401,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9.991488e+03,KOTIDO TOWN COUNCIL,KOTIDO,Y
10,266,NaN,38775,419111591,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,3.897166e+04,NAKAPERIMORU,KOTIDO,Y
11,267,NaN,65704,880955930,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,2.216095e+05,PANYANGARA,KOTIDO,Y

### DATA CLEANING OF THE COMBINED DATASET.

In [67]:
# check for nulls or missing values
comb_null = combined_df.isnull().sum()
comb_duplicates = combined_df.duplicated().sum()
comb_null
# [comb_null,comb_duplicates]

OBJECTID           0
NAME              52
POP                0
Area               0
S_Yield_Ha         0
M_Yield_Ha         0
Crop_Area_Ha       0
S_Area_Ha          0
M_Area_Ha          0
S_Prod_Tot         0
M_Prod_Tot         0
SUBCOUNTY_NAME     7
DISTRICT_NAME      7
Karamoja           7
dtype: int64

In [68]:
# filling the missing values in the column region with mean for numeric value
numeric_columns = combined_df.select_dtypes(include=[np.number]).columns
combined_df[numeric_columns] = combined_df[numeric_columns].fillna(combined_df[numeric_columns].mean())

In [69]:
# filling missing values for non-numeric columns
non_numeric_columns = combined_df.select_dtypes(exclude=[np.number]).columns
combined_df[non_numeric_columns] = combined_df[non_numeric_columns].fillna(combined_df[non_numeric_columns].mode().iloc[0])

#### DATA Cleaning Report
- filling in with a specific name for the missing (NAME,SUBCOUNTY_NAME,DISTRICT_NAME)	could distort the calculations of population density.
- Instead, We consider mode.
- For Statistical data we used mean,  to fill in missing numeric data.

In [70]:
# dataframe after cleaning
combined_df.head(12)

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot,SUBCOUNTY_NAME,DISTRICT_NAME,Karamoja
0,92,ABIM,90385,2771977106,449.000000,1040.000000,5470.068394,3277.295971,1848.621855,1.471506e+06,1.922567e+06,ABIM,KAABONG,Y
1,96,AMUDAT,101790,1643582836,205.000000,1297.000000,5765.443719,2973.423860,2733.661014,6.095520e+05,3.545558e+06,ABIM,KAABONG,Y
2,20,KAABONG,627057,7373606003,279.000000,945.000000,28121.672530,20544.194960,7394.416334,5.731830e+06,6.987723e+06,ABIM,KAABONG,Y
3,85,KOTIDO,243157,3641539808,331.000000,1148.000000,53032.649450,50247.443900,1751.372284,1.663190e+07,2.010575e+06,ABIM,KAABONG,Y
4,5,MOROTO,127811,3570160948,128.000000,355.000000,5954.814048,4741.748776,1190.050606,6.069440e+05,4.224680e+05,ABIM,KAABONG,Y
5,54,NAKAPIRIPIRIT,146780,4216323900,356.000000,1264.000000,26372.698490,19237.333210,6425.788414,6.848491e+06,8.122197e+06,ABIM,KAABONG,Y
6,80,NAPAK,167625,4508782023,137.000000,854.000000,22944.296020,16142.015880,6543.719066,2.211456e+06,5.588336e+06,ABIM,KAABONG,Y
7,263,ABIM,17244,1067176155,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,6.007239e+05,KACHERI,KOTIDO,Y
8,264,ABIM,52771,597575188,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,9.592014e+05,KOTIDO,KOTIDO,Y
9,265,ABIM,27389,23972401,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9.991488e+03,KOTIDO TOWN COUNCIL,KOTIDO,Y
10,266,ABIM,38775,419111591,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,3.897166e+04,NAKAPERIMORU,KOTIDO,Y
11,267,ABIM,65704,880955930,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,2.216095e+05,PANYANGARA,KOTIDO,Y

### Exploring Combined Data Set

In [71]:
# Size of the combined data
combined_df.shape

(59, 14)

In [72]:
# Summary of the combined data
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBJECTID        59 non-null     int64
 1   NAME            59 non-null     object
 2   POP             59 non-null     int64
 3   Area            59 non-null     int64
 4   S_Yield_Ha      59 non-null     float64
 5   M_Yield_Ha      59 non-null     float64
 6   Crop_Area_Ha    59 non-null     float64
 7   S_Area_Ha       59 non-null     float64
 8   M_Area_Ha       59 non-null     float64
 9   S_Prod_Tot      59 non-null     float64
 10  M_Prod_Tot      59 non-null     float64
 11  SUBCOUNTY_NAME  59 non-null     object
 12  DISTRICT_NAME   59 non-null     object
 13  Karamoja        59 non-null     object
dtypes: float64(7), int64(3), object(4)
memory usage: 6.6+ KB

In [73]:
# Statistical summary of the combined data
combined_df.describe()

,OBJECTID,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
count,59.000000,59.000000,5.900000e+01,59.000000,59.000000,59.000000,59.000000,59.000000,5.900000e+01,5.900000e+01
mean,701.711864,51003.542373,9.398630e+08,273.586459,945.703334,5005.479412,3971.642595,945.343375,1.156108e+06,9.695461e+05
std,353.856198,87994.178609,1.338079e+09,117.624497,319.200199,8668.593760,7654.205284,1570.917869,2.483804e+06,1.655393e+06
min,5.000000,1418.000000,2.121209e+06,108.156411,0.000000,0.171390,0.130941,0.000000,1.728126e+01,0.000000e+00
25%,592.500000,16721.000000,1.901488e+08,170.240064,757.082394,998.266305,533.066508,92.508396,1.466574e+05,7.862814e+04
50%,767.000000,26644.000000,4.997769e+08,279.000000,1030.064093,2008.068169,1550.944570,358.550335,3.397606e+05,3.069518e+05
75%,980.500000,43618.000000,1.048900e+09,361.945262,1211.009291,5616.531290,3216.917338,957.467889,9.664307e+05,9.700422e+05
max,1320.000000,627057.000000,7.373606e+09,560.313070,1396.991494,53032.649450,50247.443900,7394.416334,1.663190e+07,8.122197e+06

#### Population density

In [74]:

# Calculate the population density and add it as a new column
pop_density = combcsv_df.assign(POP_DENSITY=lambda x: x['POP'] / x['Area'])

# Select and display only the 'NAME' and 'POP_DENSITY' columns
pop_density_output = pop_density[['NAME', 'POP_DENSITY']]

# Show the first two rows
pop_density_output.head()

      NAME  POP_DENSITY
0     ABIM     0.000033
1   AMUDAT     0.000062
2  KAABONG     0.000085
3   KOTIDO     0.000067
4   MOROTO     0.000036

In [75]:
# prompt: Using dataframe pop_density_output: GRAPH

import altair as alt
alt.Chart(pop_density_output).mark_bar().encode(
    x='NAME',
    y='POP_DENSITY'
)

/usr/local/lib/python3.10/dist-packages/altair/utils/core.py:384: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [76]:
# adding a column of total production per hectare for sorghum
combined_df = df.assign(TOTAL_PROD_PER_HA = lambda x: x['S_Prod_Tot'] / x['Area'])
combined_df.head()

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot,TOTAL_PROD_PER_HA
0,92,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567,0.000531
1,96,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558,0.000371
2,20,KAABONG,627057,7373606003,279,945,28121.672530,20544.194960,7394.416334,5731830,6987723,0.000777
3,85,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575,0.004567
4,5,MOROTO,127811,3570160948,128,355,5954.814048,4741.748776,1190.050606,606944,422468,0.000170

### Exporting combined dataset

In [77]:
# saving the combined dataset
combined_df.to_csv('Karamoja_combined_df.csv', index=False)

In [78]:
combcsv_df=pd.read_csv("/content/Karamoja_combined_df.csv")
combcsv_df.head()

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot,TOTAL_PROD_PER_HA
0,92,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567,0.000531
1,96,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558,0.000371
2,20,KAABONG,627057,7373606003,279,945,28121.672530,20544.194960,7394.416334,5731830,6987723,0.000777
3,85,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575,0.004567
4,5,MOROTO,127811,3570160948,128,355,5954.814048,4741.748776,1190.050606,606944,422468,0.000170

## Summary.
The Karamoja Project focuses on addressing food insecurity in Uganda's most vulnerable region by developing a food security monitoring tool. Dalberg Data Insights (DDI) used satellite images to measure the yield of sorghum and maize, the region's staple crops. The project involved cleaning and merging datasets that include population, crop yield, and area data for Uganda’s subcounties and districts. Missing values were filled using statistical methods, ensuring data reliability. The cleaned dataset is intended for analysis and visualization using Tableau, aiding NGOs in making informed decisions to support farmers and improve food security in Karamoja.